# File: .github/workflows/maven.yml

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up JDK (Amazon Corretto 21.0.5)
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '21'
        cache: 'maven'

    - name: Build and run tests with Maven
      run: mvn clean verify
      working-directory: POE

    - name: Upload unit test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: POE/target/surefire-reports/

